{
  pkgs,
  inputs,
  ...
}: {
  home.packages = with pkgs; [
    google-chrome
    imagemagick
    grim
    grimblast
    guvcview
    slurp
    nautilus
    nautilus-open-any-terminal
    imv
    mpv
    pavucontrol
    tree
    tldr
    ffmpeg
    zip
    jp2a
    alejandra
    superfile
    discord
    smile
    nwg-displays
    libadwaita
    adwaita-icon-theme
    adwaita-qt
    adwaita-qt6
    glib
    qt6.qtwayland
    qt5.qtwayland
    qt6.qtbase
    qt6.qtdeclarative
    qt6.qtsvg
    qt6.qttools
    duf
    ncdu
    libreoffice
    papers
    anytype
    github-copilot-cli
    claude-code-bin
    gzip
    inputs.nix4gitbutler.packages.${pkgs.stdenv.hostPlatform.system}.default
    gnome-disk-utility
    thunderbird-bin
    age
    frida-tools
  ];
}
